// C++ Compiler Command Driver
// Copyright (c) 2020-2024 Grigore Stefan <g_stefan@yahoo.com>
// MIT License (MIT) <http://opensource.org/licenses/MIT>
// SPDX-FileCopyrightText: 2020-2024 Grigore Stefan <g_stefan@yahoo.com>
// SPDX-License-Identifier: MIT

#ifndef XYO_CPPCOMPILERCOMMANDDRIVER_DEPENDENCY_HPP
#define XYO_CPPCOMPILERCOMMANDDRIVER_DEPENDENCY_HPP

#ifndef XYO_SYSTEM_HPP
#	include <XYO/System.hpp>
#endif

// -- Export

#ifdef XYO_CC_INTERNAL
#	ifndef XYO_CPPCOMPILERCOMMANDDRIVER_INTERNAL
#		define XYO_CPPCOMPILERCOMMANDDRIVER_INTERNAL
#	endif
#endif

#ifdef XYO_CC_DLL_INTERNAL
#	ifndef XYO_CPPCOMPILERCOMMANDDRIVER_DLL_INTERNAL
#		define XYO_CPPCOMPILERCOMMANDDRIVER_DLL_INTERNAL
#	endif
#endif

#ifdef XYO_CPPCOMPILERCOMMANDDRIVER_DLL_INTERNAL
#	define XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT XYO_PLATFORM_LIBRARY_EXPORT
#else
#	define XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT XYO_PLATFORM_LIBRARY_IMPORT
#endif
#ifdef XYO_CPPCOMPILERCOMMANDDRIVER_LIBRARY
#	undef XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT
#	define XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT
#endif
#ifdef XYO_CC_LIB_INTERNAL
#	undef XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT
#	define XYO_CPPCOMPILERCOMMANDDRIVER_EXPORT
#endif

namespace XYO::CPPCompilerCommandDriver {
	using namespace XYO::System;
};

#endif
